language: php

os: windows

services:
    - mysql

php:
  - 7.4.6

install:
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test

script:
  - ./vendor/bin/simple-phpunit --coverage-text --colors